# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'E:\学习资料\大三上学期\离散数学\新建文件夹\DMmyeric.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(814, 766)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.edge_input = QtWidgets.QTextEdit(self.centralWidget)
        self.edge_input.setGeometry(QtCore.QRect(30, 190, 151, 201))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.edge_input.setFont(font)
        self.edge_input.setObjectName("edge_input")
        self.node_input = QtWidgets.QLineEdit(self.centralWidget)
        self.node_input.setGeometry(QtCore.QRect(30, 110, 321, 41))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(12)
        self.node_input.setFont(font)
        self.node_input.setObjectName("node_input")
        self.label = QtWidgets.QLabel(self.centralWidget)
        self.label.setGeometry(QtCore.QRect(30, 90, 131, 16))
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralWidget)
        self.label_2.setGeometry(QtCore.QRect(30, 150, 211, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.textBrowser_incidency_mat = QtWidgets.QTextBrowser(self.centralWidget)
        self.textBrowser_incidency_mat.setGeometry(QtCore.QRect(420, 60, 371, 180))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(11)
        self.textBrowser_incidency_mat.setFont(font)
        self.textBrowser_incidency_mat.setObjectName("textBrowser_incidency_mat")
        self.textBrowser_adjacency_mat = QtWidgets.QTextBrowser(self.centralWidget)
        self.textBrowser_adjacency_mat.setGeometry(QtCore.QRect(420, 280, 371, 180))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(11)
        self.textBrowser_adjacency_mat.setFont(font)
        self.textBrowser_adjacency_mat.setObjectName("textBrowser_adjacency_mat")
        self.textBrowser_reacheable_mat = QtWidgets.QTextBrowser(self.centralWidget)
        self.textBrowser_reacheable_mat.setGeometry(QtCore.QRect(420, 500, 371, 180))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(11)
        self.textBrowser_reacheable_mat.setFont(font)
        self.textBrowser_reacheable_mat.setObjectName("textBrowser_reacheable_mat")
        self.label_3 = QtWidgets.QLabel(self.centralWidget)
        self.label_3.setGeometry(QtCore.QRect(420, 30, 131, 21))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralWidget)
        self.label_4.setGeometry(QtCore.QRect(420, 250, 141, 21))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralWidget)
        self.label_5.setGeometry(QtCore.QRect(420, 470, 151, 21))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralWidget)
        self.label_6.setGeometry(QtCore.QRect(30, 70, 211, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.pushButton_confirm = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton_confirm.setGeometry(QtCore.QRect(30, 400, 281, 28))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(12)
        self.pushButton_confirm.setFont(font)
        self.pushButton_confirm.setObjectName("pushButton_confirm")
        self.combo_setting = QtWidgets.QComboBox(self.centralWidget)
        self.combo_setting.setGeometry(QtCore.QRect(140, 20, 151, 31))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(12)
        self.combo_setting.setFont(font)
        self.combo_setting.setObjectName("combo_setting")
        self.combo_setting.addItem("")
        self.combo_setting.addItem("")
        self.label_7 = QtWidgets.QLabel(self.centralWidget)
        self.label_7.setGeometry(QtCore.QRect(30, 20, 211, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.textBrowser_judge = QtWidgets.QTextBrowser(self.centralWidget)
        self.textBrowser_judge.setGeometry(QtCore.QRect(30, 500, 321, 181))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(12)
        self.textBrowser_judge.setFont(font)
        self.textBrowser_judge.setObjectName("textBrowser_judge")
        self.label_8 = QtWidgets.QLabel(self.centralWidget)
        self.label_8.setGeometry(QtCore.QRect(40, 460, 141, 31))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(12)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.pushButton_judge = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton_judge.setGeometry(QtCore.QRect(220, 460, 93, 28))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(12)
        self.pushButton_judge.setFont(font)
        self.pushButton_judge.setObjectName("pushButton_judge")
        self.label_9 = QtWidgets.QLabel(self.centralWidget)
        self.label_9.setGeometry(QtCore.QRect(550, 740, 241, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.centralWidget)
        self.label_10.setGeometry(QtCore.QRect(130, 740, 261, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.pushButton = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton.setGeometry(QtCore.QRect(680, 710, 93, 28))
        self.pushButton.setObjectName("pushButton")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralWidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(210, 190, 141, 201))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.pushButton_default_bipartite = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_default_bipartite.setObjectName("pushButton_default_bipartite")
        self.verticalLayout.addWidget(self.pushButton_default_bipartite)
        self.pushButton_default_euler = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_default_euler.setObjectName("pushButton_default_euler")
        self.verticalLayout.addWidget(self.pushButton_default_euler)
        self.pushButton_defaul_planer = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_defaul_planer.setObjectName("pushButton_defaul_planer")
        self.verticalLayout.addWidget(self.pushButton_defaul_planer)
        self.pushButton_default_not_planer = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_default_not_planer.setObjectName("pushButton_default_not_planer")
        self.verticalLayout.addWidget(self.pushButton_default_not_planer)
        MainWindow.setCentralWidget(self.centralWidget)

        self.retranslateUi(MainWindow)
        self.pushButton.clicked.connect(MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", u"图的矩阵表示器和特殊图的判断器————黄俊杰"))
        self.edge_input.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:12pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">v1,v2</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">v1,v3</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">v4,v5</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">v1,v2</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">v2,v4</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">v7,v6</p></body></html>"))
        self.node_input.setText(_translate("MainWindow", "v1,v2,v3,v4,v5,v6,v7"))
        self.label_2.setText(_translate("MainWindow", "Input edge:"))
        self.label_3.setText(_translate("MainWindow", "关联矩阵"))
        self.label_4.setText(_translate("MainWindow", "邻接/相邻矩阵"))
        self.label_5.setText(_translate("MainWindow", "可达/连通矩阵"))
        self.label_6.setText(_translate("MainWindow", "Input node:"))
        self.pushButton_confirm.setText(_translate("MainWindow", "确认节点和边"))
        self.combo_setting.setItemText(0, _translate("MainWindow", "无向图"))
        self.combo_setting.setItemText(1, _translate("MainWindow", "有向图"))
        self.label_7.setText(_translate("MainWindow", "Setting:"))
        self.label_8.setText(_translate("MainWindow", "特殊图的判断"))
        self.pushButton_judge.setText(_translate("MainWindow", "开始判断"))
        self.label_9.setText(_translate("MainWindow", "Copyright:黄俊杰 16031155"))
        self.label_10.setText(_translate("MainWindow", "BUAA 离散数学大作业 郑征老师"))
        self.pushButton.setText(_translate("MainWindow", "EXIT"))
        self.pushButton_default_bipartite.setText(_translate("MainWindow", "载入默认二部图"))
        self.pushButton_default_euler.setText(_translate("MainWindow", "载入默认欧拉图"))
        self.pushButton_defaul_planer.setText(_translate("MainWindow", "载入默认平面图"))
        self.pushButton_default_not_planer.setText(_translate("MainWindow", "载入默认非平面图"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

